language: r
dist: xenial
warnings_are_errors: true
sudo: false
cache: packages

addons:
  apt:
    update: true
    packages:
      - libmagick++-dev

before_install:
  - chmod 755 ./.push_gh_pages.sh

after_success:
  - Rscript -e 'covr::coveralls()'
  - test $TRAVIS_BRANCH = "stable" && test $TRAVIS_PULL_REQUEST = "false" && ./.push_gh_pages.sh
