language: r
warnings_are_errors: false
sudo: false
cache: packages
r_github_packages:
  - jimhester/covr

before_install:
  - chmod 755 ./.push_gh_pages.sh

after_success:
  - Rscript -e 'covr::coveralls()'
  - ./.push_gh_pages.sh
