version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest
    steps:
      - restore_cache:
          keys:
            - cache
      - checkout
      - run:
          name: Install apt dependencies
          command: |
            apt-get update
            apt-get install libmagick++-dev -y
            tlmgr install amsfonts
      - run:
          name: Install R package dependencies
          command: |
            R -e 'install.packages("remotes")'
            R -e 'remotes::install_deps(dependencies = TRUE)'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - run:
          name: Warnings as errors
          command: | 
            if ! grep -q -R "WARNING" /root/project/${CIRCLE_PROJECT_REPONAME}.Rcheck/00check.log
            then
              exit 0
            else
              exit 1
            fi
          when: on_success
      - run:
          name: R CMD check logs - failure
          command: |
            for name in $(find "/root/project/${CIRCLE_PROJECT_REPONAME}.Rcheck/tests/" -type f -name "*fail");do echo ">>> Filename: ${name} <<<";cat ${name};done
          when: on_fail
      - run:
          name: R CMD check logs - log
          command: |
            cat /root/project/${CIRCLE_PROJECT_REPONAME}.Rcheck/00check.log
          when: on_fail
      - run:
          name: Code coverage report (codecov.io)
          command: |
            Rscript -e 'covr::codecov()'
          when: on_success
      - save_cache:
          key: cache
          paths:
            - "/usr/local/lib/R/site-library"
  publish-github-release:
    requires:
      - build
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v\d+\.\d+\.\d+$/
    docker:
      - image: cibuilds/github
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/${CIRCLE_PROJECT_REPONAME}/*tar.gz
