version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest
    steps:
      - restore_cache:
          keys:
            - cache
      - checkout
      - run:
          name: Install apt dependencies
          command: |
            apt-get update
            apt-get install libmagick++-dev -y
      - run:
          name: Install R package dependencies
          command: |
            R -e 'install.packages("remotes")'
            R -e 'remotes::install_deps(dependencies = TRUE)'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - run:
          name: Warnings as errors
          command: grep -q -R "WARNING" /root/project/arphit.Rcheck/00check.log
      - run:
          name: R CMD check logs - failure
          command: for name in $(find "/root/project/arphit.Rcheck/tests/" -type f -name "*fail");do echo ">>> Filename: ${name} <<<";cat ${name};done
          when: on_fail
      - save_cache:
          key: cache
          paths:
            - "/usr/local/lib/R/site-library"
