DEFAULTCOLORS <- c("black","blue","grey","green")
CSI <- 0.2 # This may change in different environments, but I don't know...
LANDSCAPESIZE <- c(4.5,5)
PORTRAITSIZE <- c(7,5)
PERMITTEDLABELS <- c(1,1.5,2,2.5,3,5)
PERMITTEDSTEPS <- c(4,5,6,7)
MAXXYEARS <- 8
DEFAULTSCALEUNITS <- "%"
NSPACESNOTES <- 8
NSPACESSOURCES <- 17
LINELENGTHNOTES <- 55
LINELENGTHSOURCES <- LINELENGTHNOTES - (NSPACESNOTES - NSPACESSOURCES)
DEFAULTPCH <- NA
DEFAULTLTY <- 1
DEFAULTLWD <- 1
EMPTYSCALE <- list("min" = -1, "max" = 2, "nsteps" = 4)
DEFAULTTICKLENGTH <- 0.02
DEFAULTBARCOL <- NA
PNGDPI <- 300
