DEFAULTCOLORS <- c(RBA["Aqua8"], RBA["Orange2"], RBA["DarkGreen7"], RBA["Violet1"], RBA["Blue7"], RBA["Red5"], RBA["Brown4"], RBA["Pink2"], RBA["Grey7"])
CSI <- 0.2 # This may change in different environments, but I don't know...
LANDSCAPESIZE <- c(0.736842 * 7.5,7.5)
PORTRAITSIZE <- c(10, 7.5)
PERMITTEDLABELS <- c(1,1.5,2,2.5,3,5)
PERMITTEDSTEPS <- c(4,5,6,7)
MAXXYEARS <- 8
DEFAULTSCALEUNITS <- "%"
NSPACESNOTES <- 8
NSPACESSOURCES <- 17
LINELENGTHNOTES <- 55
LINELENGTHSOURCES <- LINELENGTHNOTES - (NSPACESNOTES - NSPACESSOURCES)
DEFAULTPCH <- NA
DEFAULTLTY <- 1
DEFAULTLWD <- 1
EMPTYSCALE <- list("min" = -1, "max" = 2, "nsteps" = 4)
DEFAULTTICKLENGTH <- 0.02
DEFAULTBARCOL <- NA
DEFAULTSHADINGCOLOR <- "lightgrey"
PNGDPI <- 300
MINIMUMSIDEPADDING <- 0.9
