DEFAULTCOLORS <- c(RBA["Aqua8"], RBA["Orange2"], RBA["DarkGreen7"], RBA["Violet1"], RBA["Blue7"], RBA["Red5"], RBA["Brown4"], RBA["Pink2"], RBA["Grey7"])
CSI <- 0.2
LANDSCAPESIZE <- c(0.736842 * 7.5,7.5)
PORTRAITSIZE <- c(10, 7.5)
PERMITTEDLABELS <- c(1,1.5,2,2.5,3,5)
PERMITTEDSTEPS <- c(4,5,6,7)
DEFAULTSCALEUNITS <- "%"
NSPACESNOTES <- 8
NSPACESSOURCES <- 17
LINELENGTHNOTES <- 55
LINELENGTHSOURCES <- LINELENGTHNOTES - (NSPACESNOTES - NSPACESSOURCES)
LINELENGTHTITLE <- 60
LINELENGTHSUBTITLE <- 75
LINELENGTHPANELTITLE <- 45
LINELENGTHPANELSUBTITLE <- 55
DEFAULTPCH <- NA
DEFAULTLTY <- 1
DEFAULTLWD <- 2
EMPTYSCALE <- list("min" = -1, "max" = 2, "nsteps" = 4)
EMPTYXSCALE <- c(2000,2010)
DEFAULTTICKLENGTH <- 0.02
DEFAULTBARCOL <- NA
DEFAULTSHADINGCOLOR <- "lightgrey"
DEFAULTARROWLWD <- 1
PNGDPI <- 300
MINIMUMSIDEPADDING <- 0.4
MAXXLABELS <- 8
MAXLEGENDCHARS <- 45
